// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab_13_data.Data;

namespace lab_13_data.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20200529050303_seeding_tables")]
    partial class seeding_tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lab_13_data.Models.Amenities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomsId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "tv"
                        },
                        new
                        {
                            Id = 2,
                            Name = "toaster"
                        },
                        new
                        {
                            Id = 3,
                            Name = "hair dryer"
                        });
                });

            modelBuilder.Entity("lab_13_data.Models.HotelRoom", b =>
                {
                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<bool>("PetFrindly")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.HasKey("HotelId", "Number");

                    b.HasIndex("RoomID");

                    b.ToTable("HotelRoom");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            Number = 250,
                            PetFrindly = false,
                            Rate = 9.5m,
                            RoomID = 1
                        },
                        new
                        {
                            HotelId = 1,
                            Number = 20,
                            PetFrindly = false,
                            Rate = 5m,
                            RoomID = 2
                        },
                        new
                        {
                            HotelId = 1,
                            Number = 300,
                            PetFrindly = false,
                            Rate = 10m,
                            RoomID = 3
                        },
                        new
                        {
                            HotelId = 2,
                            Number = 250,
                            PetFrindly = true,
                            Rate = 9.5m,
                            RoomID = 4
                        });
                });

            modelBuilder.Entity("lab_13_data.Models.Hotels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "north liberty",
                            Name = "mercure",
                            StreetName = "progress st"
                        },
                        new
                        {
                            Id = 2,
                            City = "north liberty",
                            Name = "hilton",
                            StreetName = "marylyn dr "
                        },
                        new
                        {
                            Id = 3,
                            City = "north liberty",
                            Name = "azure",
                            StreetName = "H st"
                        });
                });

            modelBuilder.Entity("lab_13_data.Models.RoomAmenities", b =>
                {
                    b.Property<int>("AmenitiesId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("AmenitiesId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomAmenities");

                    b.HasData(
                        new
                        {
                            AmenitiesId = 1,
                            RoomId = 1
                        },
                        new
                        {
                            AmenitiesId = 2,
                            RoomId = 1
                        },
                        new
                        {
                            AmenitiesId = 3,
                            RoomId = 1
                        },
                        new
                        {
                            AmenitiesId = 1,
                            RoomId = 2
                        });
                });

            modelBuilder.Entity("lab_13_data.Models.Rooms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Layout = 0,
                            RoomName = "red"
                        },
                        new
                        {
                            Id = 2,
                            Layout = 0,
                            RoomName = "bleu"
                        },
                        new
                        {
                            Id = 3,
                            Layout = 0,
                            RoomName = "pink"
                        },
                        new
                        {
                            Id = 4,
                            Layout = 0,
                            RoomName = "purple"
                        });
                });

            modelBuilder.Entity("lab_13_data.Models.Amenities", b =>
                {
                    b.HasOne("lab_13_data.Models.Rooms", null)
                        .WithMany("Amenities")
                        .HasForeignKey("RoomsId");
                });

            modelBuilder.Entity("lab_13_data.Models.HotelRoom", b =>
                {
                    b.HasOne("lab_13_data.Models.Hotels", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab_13_data.Models.Rooms", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lab_13_data.Models.RoomAmenities", b =>
                {
                    b.HasOne("lab_13_data.Models.Amenities", "Amenities")
                        .WithMany()
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab_13_data.Models.Rooms", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
